### ISSUE TITLE
TokenRequestFailed

### ISSUE THREAD

**Issue by FelixGail** [svarzee/gpsoauth-java#11]
I am trying to use this library for an up-to-date PlayMusic library.
Could you provide me with a little information on how to use yours?

Does the OKHttpClient provided with the login need to meet any specifications?
How can i provide a Client signature?

I created an app password and `performMasterLoginForToken()` returns a token, but it fails afterwards.

**Comment by FelixGail** [comment]
I found the solution. The Google service i was using (PlayMusic) would not return an expiry date. Since this repo seems dead the updated version can be found on https://github.com/BjoernPetersen/gpsoauth-java

**Comment by svarzee** [comment]
Since v0.4.0 expiry defaults to -1 if not received.
