### ISSUE TITLE
Master token request failing

### ISSUE THREAD

**Issue by FelixGail** [svarzee/gpsoauth-java#16]
It looks like the master token request stopped working.
```
Caused by: svarzee.gps.gpsoauth.Gpsoauth$TokenRequestFailed
	at svarzee.gps.gpsoauth.Gpsoauth.performMasterLoginForToken(Gpsoauth.java:104)
	at svarzee.gps.gpsoauth.Gpsoauth.performMasterLoginForToken(Gpsoauth.java:90)
	at svarzee.gps.gpsoauth.Gpsoauth.login(Gpsoauth.java:38)
```
It looks like https://github.com/simon-weber/gpsoauth only updated the request version used. Are you still maintining this library?

**Comment by svarzee** [comment]
@FelixGail It's been a long time since I last touched this code but I will have a look at this.

**Comment by svarzee** [comment]
@FelixGail I cannot replicate your problem. Does the problem still persist?

**Comment by umjammer** [comment]
i got the same problem with oracle jdk 8 and open jdk 13.
but with graal vm 8, it works fine.

✅
```
$ java -version 
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-20191009173705.graal.jdk8u-src-tar-gz-b07)
OpenJDK 64-Bit GraalVM CE 19.3.0 (build 25.232-b07-jvmci-19.3-b05, mixed mode)
```

🚫
```
$ java -version
openjdk version "13" 2019-09-17
OpenJDK Runtime Environment (build 13+33)
OpenJDK 64-Bit Server VM (build 13+33, mixed mode, sharing)

$ java -version                          
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
```

enabling okhttp logging, i found the only difference is `EncryptedPasswd`. but it changes every time. so i could not determine what is wrong...

**Comment by svarzee** [comment]
For me it works fine on HotSpot

> java version "1.8.0_231"
> Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
> Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
>

**Comment by svarzee** [comment]
I replicated the problem using hotspot 1.8.0_231. It works fine for openjdk 1.8.0_212.
I listened on localhost and seeded the random generator so that encrypted password remains the same and the requests are exactly the same for both openjdk and hotspot. The only difference is that I listen on http while google listens on https.

I also discovered that upgrading okhttp to 3.5.0 introduces the problem even on openjdk.
I found the changes that break compatibility: https://github.com/square/okhttp/pull/2690

Replacing sun.security.ssl classes with openjdk implementation makes the problem disappear.

**Comment by svarzee** [comment]
#17

**Comment by svarzee** [comment]
Fix at 0.6.0, tested with:
- 1.8.0_231, x86_64:	"Java SE 8"
- 1.8.0_212, x86_64:	"AdoptOpenJDK 8"

**Comment by svarzee** [comment]
For the fix to work you must use the no parameters constructor of Gpsoauth. The trick is that OkHttpClient must be constructed with propert SSL implementation.

**Comment by ZPetrovich** [comment]
@svarzee It's still does not work. Checked with 
```
java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```
could you please take a look?
