### ISSUE TITLE
Can't get token on android

### ISSUE THREAD

**Issue by benjy3gg** [svarzee/gpsoauth-java#3]
I'm using it together with PokeGO-Api in my Android app.
I get 403 Bad Authenitcation Error when the function performMasterLogin is called.
can you test it pls?

I fetched your PR and applied it.

**Comment by svarzee** [comment]
I did not observe this problem myself.
Are u sure u are passing correct credentials?
Your problem might as well be related to this https://github.com/svarzee/gpsoauth-java/pull/1#issuecomment-235939812
