### ISSUE TITLE
Compatibility to Java 1.7

### ISSUE THREAD

**Issue by mgorski-mg** [svarzee/gpsoauth-java#5]
You probably use only Base64 class from Java 1.8 so it should be easy to make it compatible with previous version. 
It should be compatible with Java 1.7 as you are using it inside PokeGOAPI-Java library.

**Comment by mgorski-mg** [comment]
Ok, it's done in PR https://github.com/svarzee/gpsoauth-java/pull/1
It requires some refactor but it fixes this problem.

**Comment by john086** [comment]
i include PokeGOAPI-Java library in my android application and when run it i give this error.

Error:Execution failed for task ':app:transformClassesWithDexForDebug'.

> com.android.build.api.transform.TransformException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process
> Error:Error converting bytecode to dex:
> Cause: Dex cannot parse version 52 byte code.
> This is caused by library dependencies that have been compiled using Java 8 or above.
> If you are using the 'java' gradle plugin in a library submodule add 
> targetCompatibility = '1.7'
> sourceCompatibility = '1.7'
> to that submodule's build.gradle file.

**Comment by svarzee** [comment]
v0.3.0 targets 1.7

**Comment by AbandonedCart** [comment]
v0.3.0 hangs on `Configuring > 1/1 projects > Resolving dependencies ':compile'`
